### PR TITLE
Fix symbol IDs assigned to encoding packets

### LINKED ISSUE #164: Possible inconsistency with RFC 6330: use of ISI vs ESI in `PayloadId`
First of all, thank you very much for maintaining this efficient RaptorQ library, this is highly appreciated. 💯 

While integrating this into one of my projects, I believe I found an inconsistency of the library's behavior with RFC 6330.

[RFC 6330, Section 5.3.1](https://datatracker.ietf.org/doc/html/rfc6330#section-5.3.1) states the following (emphasis added):
> For a given source block of `K` source symbols, for encoding and decoding purposes, the source block is augmented with `K'-K` additional padding symbols [...]
The encoding symbol ID (ESI) is used by a sender and receiver to identify the encoding symbols of a source block, [...].  For a source block with `K` source symbols, **the ESIs for the source symbols are `0, 1, 2, ..., K-1`, and the ESIs for the repair symbols are `K, K+1, K+2, ...`**.  Using the ESI for identifying encoding symbols in transport ensures that the ESI values continue consecutively between the source and repair symbols.

What I get when running the code, however, is a gap between the source and repair symbols, which should only be there for the internal symbol ID (ISI):
> For purposes of encoding and decoding data, the value of `K'` derived from `K` is used as the number of source symbols of the extended source block upon which encoding and decoding operations are performed, where the `K'` source symbols consist of the original `K` source symbols and an additional `K'-K` padding symbols.  The Internal Symbol ID (ISI) is used by the encoder and decoder to identify the symbols associated with the extended source block, i.e., for generating encoding symbols and for decoding.  For a source block with `K` original source symbols, the ISIs for the original source symbols are `0, 1, 2, ..., K-1`, the ISIs for the `K'-K` padding symbols are `K, K+1, K+2, ..., K'-1`, and the ISIs for the repair symbols are `K', K'+1, K'+2, ...`.

AFAIU the RFC, the `PayloadId` should contain the ESI, but the library actually adds the ISI (in [`SourceBlockEncoder::repair_packets`](https://github.com/cberner/raptorq/blob/master/src/encoder.rs#L314)). Using the ESI instead of the ISI would also prevent potential panics in [`decode`](https://github.com/cberner/raptorq/blob/master/src/decoder.rs#L264).

**Example code:**
```rust
use raptorq::{Encoder, ObjectTransmissionInformation};

fn main() {
    let encoder = Encoder::new(
        &[1, 2, 3],
        ObjectTransmissionInformation::new(3, 1, 1, 0, 1),
    );
    for packet in encoder.get_encoded_packets(3) {
        println!("{}", packet.payload_id().encoding_symbol_id());
    }
}
```

**Example output (`K'=10` for `K=3`):**
```
0
1
2
10
11
12
```

### PR DESCRIPTION
**Pull request by mlegner**
Previously, we incorrectly assigned internal symbol IDs (ISIs) to the `PayloadId` of `EncodingPacket`s. According to RFC 6330, it should be the encoding symbol IDs (ESIs). This commit fixes this inconsistency.

BREAKING CHANGE: As the assignment of symbol IDs changes, encoding packets generated before this change cannot be decoded by the new version and vice-versa.

Closes #164

### CODE REVIEW

File: src/encoder.rs [hunk 1]
```diff
@@ -321,7 +321,7 @@ impl SourceBlockEncoder {
         for i in 0..packets {
             let tuple = intermediate_tuple(start_encoding_symbol_id + i, lt_symbols, sys_index, p1);
             result.push(EncodingPacket::new(
-                PayloadId::new(self.source_block_id, start_encoding_symbol_id + i),
+                PayloadId::new(self.source_block_id, self.source_symbols.len() as u32 + i),
```
Comment (cberner) [inline src/encoder.rs:324]: I think this needs to include `+ start_repair_symbol_id` here

**Review by cberner — COMMENTED** [review]
Left one comment. Can you check that? Otherwise it looks good to me

File: src/encoder.rs (hunk 1 above)
Comment (mlegner) [reply src/encoder.rs]: You are right, thanks a lot for spotting that.

I've changed this and added a test that would have caught that bug.
